import { Inter } from 'next/font/google'
import Asidebar from '../components/Asidebar'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='homegrid'>
                    <Navbar />
                    <Asidebar />
                    <div className='main-content'>

                        {children}

                    </div>
                </div>

            </body>
        </html>
    )
}
